### ISSUE TITLE
XLS-1d Standard for inter-contract communication

### ISSUE THREAD

**Issue by RichardAH** [xrp-community/standards-drafts#2]
I'm going to suggest: https://github.com/elpheria/rpc-websockets

Happy to hear thoughts

**Comment by WietseWind** [comment]
Can you elaborate on the use case? Where should this be implemented?

**Comment by codetsunami** [comment]
There was some debate as to whether or not XLS standards should encompass all the standards needed for Codius and ILP as well as direct XRP ledger standards. It is of course possible to set up separate standards letterings for Codius and ILP and put them in their own git. E.g. CLS-123, ILS-123. However after thinking about it for some time I've come to the conclusion that we should seek to include as many XRPL ecosystem standards under the one numbering system as possible.

The point of publishing standards is to make standard documents easily accessible and in particular easy to look up. XLS gives us one place to look up, refer to and debate all XRPL community ecosystem standards. This is also consistent with the likes of W3C, RFC, and ISO, using the same numbering system for a wide range of standards.

All of that said XLS-1d is supposed to define the way Codius contracts talk to eachother and to the outside world. This is functionality I want to add to Toast in the version after next so that it can talk to a Codius project I am working on.

JSON-RPC over websockets seems the obvious starting point for this. We need to take into consideration the unique constraints of working with contracts. (Keeping in mind that contracts can be blackboxes.)

Here's some things that need to be discussed and thought about:
- a standard protocol for the enforcement of byzantine replicated state across the various instances of a codius contract 
- connection and query timeouts
- automatic and reliable reconnection to a group of hosts
- at most once / at least once call and other call guarantees
- long running calls with multiple returns (subscriptions)
- synchronous call support
- synchronous call support when one contract must wait on another
- security (contract instance identity, signatures)
- ddos protection, and a standard way to stop overuse of resources by greedy users
- interface discovery (like Microsoft's COM QueryInterface)

**Comment by codetsunami** [comment]
Unfinished version of the standard is here: https://github.com/xrp-community/standards-drafts/tree/master/xls-1d

**Comment by WietseWind** [comment]
Wow @codetsunami you've been busy! Looking great!

**Comment by codetsunami** [comment]
Even though I have a reference implementation mostly done I think we need to be careful not to dictate how an implementation must specifically work. For example it doesn't matter for the purpose of the standard how `requests` are actually sequenced and how specifically the BFT consensus occurs. All the matters is that it does occur and that each instance applies the same sequence of inputs (requests) at about the same time. This is complicated by the fact that IIC messages are being defined in the standard which more or less do dictate the implementation specifics. I may need to break the standard into two parts: a set of blackbox interfaces and an glassbox advisory.

**Comment by codetsunami** [comment]
I decided this standard was far too specific and really just needed to be a project.

https://github.com/codetsunami/hotpocket/

I will replace XLS-1d with just the public communication component (I.e. what a user needs to do to connect to and talk to a smart contract)
